version: '3.9'

services:
  mongo_db:
    container_name: db_container
    image: mongo
    restart: always
    ports:
      - '2717:27017'
    volumes:
      - mongo_data:/data/db

  api:
    container_name: api_node
    build: .
    ports:
      - '4000:3000'
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      SECRETORKEY_JWT: sWEhOSNWdG32-344s_sdsADJ45-fedDFGGHTX
    links:
      - mongo_db
    depends_on:
      - mongo_db
    volumes:
      - .:/usr/src/app

volumes:
  mongo_data:
